"""Sync ConversationModel

# pylint: disable=no-member

Revision ID: 439174cb8c5e
Revises: b7f5a5c7d9e1
Create Date: 2026-02-10 18:53:13.035546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '439174cb8c5e'
down_revision: Union[str, Sequence[str], None] = 'b7f5a5c7d9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create dependent tables first (referenced by FKs)
    # We recreate tables that might be missing or ensure they exist with correct schema
    
    # Check if table exists before creating to avoid errors in some edge cases on clean DBs
    # In a real migration we usually just create, but here we are syncing state
    
    # Safe checks for contents table
    op.execute('''
        CREATE TABLE IF NOT EXISTS contents (
            id UUID PRIMARY KEY,
            type VARCHAR(50) NOT NULL,
            text TEXT,
            caption TEXT,
            title VARCHAR(255),
            description TEXT,
            tags VARCHAR(500),
            has_audio BOOLEAN DEFAULT false NOT NULL,
            audio_url VARCHAR(500),
            transcription TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT content_type_check CHECK (type IN ('text', 'image', 'voice', 'video', 'document', 'location'))
        )
    ''')
    # Indices for contents
    op.execute('CREATE INDEX IF NOT EXISTS ix_contents_tags ON contents (tags)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_contents_title ON contents (title)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_contents_type ON contents (type)')

    # content_locations
    op.execute('''
        CREATE TABLE IF NOT EXISTS content_locations (
            id UUID PRIMARY KEY,
            content_id UUID NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
            latitude FLOAT NOT NULL,
            longitude FLOAT NOT NULL,
            title VARCHAR(500)
        )
    ''')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_content_locations_content_id ON content_locations (content_id)')

    # content_media
    op.execute('''
        CREATE TABLE IF NOT EXISTS content_media (
            id UUID PRIMARY KEY,
            content_id UUID NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
            mimetype VARCHAR(255) NOT NULL,
            filename VARCHAR(500) NOT NULL,
            url TEXT NOT NULL
        )
    ''')
    op.execute('CREATE INDEX IF NOT EXISTS ix_content_media_content_id ON content_media (content_id)')

    # contexts table (needed for context_items)
    op.execute('''
        CREATE TABLE IF NOT EXISTS contexts (
            id VARCHAR(36) PRIMARY KEY,
            topic_id VARCHAR(36) NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            active BOOLEAN NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
        )
    ''')
    op.execute('CREATE INDEX IF NOT EXISTS ix_contexts_active ON contexts (active)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_contexts_name ON contexts (name)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_contexts_topic_id ON contexts (topic_id)')

    # context_embeddings
    op.execute('''
        CREATE TABLE IF NOT EXISTS context_embeddings (
            id VARCHAR(36) PRIMARY KEY,
            context_id VARCHAR(36) NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
            embedding_text TEXT NOT NULL,
            chroma_doc_id VARCHAR(255),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
        )
    ''')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_context_embeddings_chroma_doc_id ON context_embeddings (chroma_doc_id)')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_context_embeddings_context_id ON context_embeddings (context_id)')

    # context_items
    op.execute('''
        CREATE TABLE IF NOT EXISTS context_items (
            id VARCHAR(36) PRIMARY KEY,
            context_id VARCHAR(36) NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
            content_id UUID NOT NULL REFERENCES contents(id) ON DELETE CASCADE,
            item_order INTEGER NOT NULL,
            context_hint TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT uq_context_items_context_order UNIQUE (context_id, item_order)
        )
    ''')
    op.execute('CREATE INDEX IF NOT EXISTS ix_context_items_content_id ON context_items (content_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_context_items_context_id ON context_items (context_id)')

    # Drop old/orphaned tables safely using CASCADE
    op.execute('DROP TABLE IF EXISTS playbook_steps CASCADE')
    op.execute('DROP TABLE IF EXISTS playbook_embeddings CASCADE')
    op.execute('DROP TABLE IF EXISTS playbooks CASCADE')
    op.execute('DROP TABLE IF EXISTS message_media CASCADE')
    op.execute('DROP TABLE IF EXISTS message_location CASCADE')
    op.execute('DROP TABLE IF EXISTS messages CASCADE')

    # Add missing columns to conversations
    op.execute('ALTER TABLE conversations ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP WITHOUT TIME ZONE')
    op.execute('COMMENT ON COLUMN conversations.closed_at IS \'When conversation was closed\'')
    
    op.execute('ALTER TABLE conversations ADD COLUMN IF NOT EXISTS is_urgent BOOLEAN DEFAULT false NOT NULL')
    op.execute('COMMENT ON COLUMN conversations.is_urgent IS \'Urgency flag\'')
    
    op.execute('ALTER TABLE conversations ADD COLUMN IF NOT EXISTS meta_data JSON DEFAULT \'{}\' NOT NULL')
    op.execute('COMMENT ON COLUMN conversations.meta_data IS \'Extra structured metadata\'')

    # Alter existing columns
    op.execute('ALTER TABLE lead_interactions ALTER COLUMN user_id DROP NOT NULL')
    op.execute('COMMENT ON COLUMN lead_interactions.user_id IS \'User who performed the interaction (NULL for bot interactions)\'')

    op.execute('ALTER TABLE leads ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITHOUT TIME ZONE')
    op.execute('COMMENT ON COLUMN leads.deleted_at IS \'Soft delete timestamp\'')

    # Fix webhook_logs payload type
    # Postgres JSON vs JSONB handling in Alembic can be tricky, using raw SQL to be safe
    op.execute('ALTER TABLE webhook_logs ALTER COLUMN payload TYPE JSON USING payload::json')


def downgrade() -> None:
    """Downgrade schema."""
    # Simplified downgrade - mostly reversing add columns
    op.execute('ALTER TABLE webhook_logs ALTER COLUMN payload TYPE JSONB USING payload::jsonb')
    op.execute('ALTER TABLE leads DROP COLUMN IF EXISTS deleted_at')
    
    op.execute('ALTER TABLE lead_interactions ALTER COLUMN user_id SET NOT NULL')
    op.execute('COMMENT ON COLUMN lead_interactions.user_id IS \'User who performed the interaction\'')

    op.execute('ALTER TABLE conversations DROP COLUMN IF EXISTS meta_data')
    op.execute('ALTER TABLE conversations DROP COLUMN IF EXISTS is_urgent')
    op.execute('ALTER TABLE conversations DROP COLUMN IF EXISTS closed_at')
    
    # We won't recreate the dropped tables in downgrade for simplicity/safety
    # expecting that if we downgrade we might restore from backup or unrelated
