# pylint: disable=no-member,invalid-name,line-too-long
"""Increase phone_number and related fields to 64 chars for WhatsApp compatibility

Revision ID: 9d9796c95ff4
Revises: 6c8e40de2a6f
Create Date: 2026-01-19 10:40:10.940503

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d9796c95ff4"
down_revision: str | Sequence[str] | None = "6c8e40de2a6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_messages",
        "from_phone",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        comment="Sender phone number or chat JID (up to 64 chars)",
        existing_comment="Sender phone number",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_messages",
        "to_phone",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        comment="Recipient phone number or chat JID (up to 64 chars)",
        existing_comment="Recipient phone number",
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "phone_number",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        comment="Contact phone number or chat JID (up to 64 chars)",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_credentials_reset_token"), "credentials", type_="unique")
    op.drop_index(op.f("ix_credentials_reset_token"), table_name="credentials")
    op.create_index(op.f("ix_credentials_reset_token"), "credentials", ["reset_token"], unique=True)
    op.alter_column(
        "leads",
        "phone_number",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=64),
        comment="Contact phone number or chat JID (up to 64 chars)",
        existing_comment="Contact phone number",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "leads",
        "phone_number",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        comment="Contact phone number",
        existing_comment="Contact phone number or chat JID (up to 64 chars)",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_credentials_reset_token"), table_name="credentials")
    op.create_index(op.f("ix_credentials_reset_token"), "credentials", ["reset_token"], unique=False)
    op.create_unique_constraint(
        op.f("uq_credentials_reset_token"), "credentials", ["reset_token"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "conversations",
        "phone_number",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Contact phone number or chat JID (up to 64 chars)",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_messages",
        "to_phone",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        comment="Recipient phone number",
        existing_comment="Recipient phone number or chat JID (up to 64 chars)",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_messages",
        "from_phone",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=20),
        comment="Sender phone number",
        existing_comment="Sender phone number or chat JID (up to 64 chars)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
