# pylint: disable=no-member,invalid-name,line-too-long
"""initial_schema

Revision ID: e75f64ab040b
Revises:
Create Date: 2026-01-03 21:14:05.087437

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e75f64ab040b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    op.create_index(op.f("ix_alerts_level"), "alerts", ["level"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "chat_id", sa.String(length=100), nullable=False, comment="WhatsApp chat ID (e.g., '5511999999999@c.us')"
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True, comment="Contact name"),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE_BOT",
                "PENDING_HANDOFF",
                "ACTIVE_HUMAN",
                "COMPLETED",
                "ESCALATED",
                "CLOSED",
                name="conversationstatus",
            ),
            nullable=False,
            comment="Current conversation status",
        ),
        sa.Column(
            "escalation_reason",
            sa.String(length=50),
            nullable=True,
            comment="Reason for escalation (scheduling_request, issue, sentiment)",
        ),
        sa.Column("escalated_at", sa.DateTime(), nullable=True, comment="When conversation was escalated"),
        sa.Column("last_message_at", sa.DateTime(), nullable=False, comment="Timestamp of last message"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_chat_id"), "conversations", ["chat_id"], unique=True)
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    op.create_index(op.f("ix_conversations_last_message_at"), "conversations", ["last_message_at"], unique=False)
    op.create_index(op.f("ix_conversations_phone_number"), "conversations", ["phone_number"], unique=False)
    op.create_index(op.f("ix_conversations_status"), "conversations", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("has_audio", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("transcription", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "type IN ('text', 'image', 'voice', 'video', 'document', 'location')", name="message_type_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_tags"), "messages", ["tags"], unique=False)
    op.create_index(op.f("ix_messages_title"), "messages", ["title"], unique=False)
    op.create_index(op.f("ix_messages_type"), "messages", ["type"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.String(length=50), nullable=False, comment="Notification type: NEW_LEAD, NEW_MESSAGE, etc."
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revoked_tokens_id"), "revoked_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_revoked_tokens_token"), "revoked_tokens", ["token"], unique=True)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=50), nullable=False, comment="Unique tag name (e.g., 'urgent', 'follow-up', 'vip')"
        ),
        sa.Column(
            "color", sa.String(length=7), nullable=False, comment="Hex color code for UI display (e.g., '#FF5733')"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Tag creation timestamp"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_table(
        "topics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topics_active"), "topics", ["active"], unique=False)
    op.create_index(op.f("ix_topics_category"), "topics", ["category"], unique=False)
    op.create_index(op.f("ix_topics_name"), "topics", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "webhook_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_name", sa.String(length=50), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False, comment="message, message.ack, etc."),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Full webhook payload"),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True, comment="Processing error if any"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_logs_created_at"), "webhook_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_webhook_logs_event_type"), "webhook_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_webhook_logs_id"), "webhook_logs", ["id"], unique=False)
    op.create_index(op.f("ix_webhook_logs_processed"), "webhook_logs", ["processed"], unique=False)
    op.create_index(op.f("ix_webhook_logs_session_name"), "webhook_logs", ["session_name"], unique=False)
    op.create_table(
        "whatsapp_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="STOPPED, STARTING, SCAN_QR_CODE, WORKING, FAILED"
        ),
        sa.Column("webhook_url", sa.Text(), nullable=True),
        sa.Column("qr_code", sa.Text(), nullable=True, comment="Base64 QR code image"),
        sa.Column("connected_phone", sa.String(length=20), nullable=True, comment="Connected WhatsApp number"),
        sa.Column("connected_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_whatsapp_sessions_id"), "whatsapp_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_whatsapp_sessions_is_active"), "whatsapp_sessions", ["is_active"], unique=False)
    op.create_index(op.f("ix_whatsapp_sessions_name"), "whatsapp_sessions", ["name"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_token_jti", sa.String(length=255), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_sessions_id"), "auth_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_auth_sessions_is_revoked"), "auth_sessions", ["is_revoked"], unique=False)
    op.create_index(op.f("ix_auth_sessions_refresh_token_jti"), "auth_sessions", ["refresh_token_jti"], unique=True)
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "conversation_contexts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False, comment="One context per conversation"),
        sa.Column("patient_name", sa.String(length=255), nullable=True, comment="Extracted patient name if provided"),
        sa.Column(
            "symptoms",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Structured symptoms data (e.g., {'pain': 'headache', 'duration': '2 days'})",
        ),
        sa.Column(
            "concerns", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Patient concerns and questions"
        ),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Scheduling preferences, location, etc.",
        ),
        sa.Column(
            "intent_detected", sa.Boolean(), nullable=False, comment="Whether user intent was successfully detected"
        ),
        sa.Column(
            "intent_type",
            sa.String(length=50),
            nullable=True,
            comment="Type of intent (scheduling, question, complaint, etc.)",
        ),
        sa.Column("summary", sa.Text(), nullable=True, comment="LLM-generated conversation summary"),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_contexts_conversation_id"), "conversation_contexts", ["conversation_id"], unique=True
    )
    op.create_index(op.f("ix_conversation_contexts_id"), "conversation_contexts", ["id"], unique=False)
    op.create_index(
        op.f("ix_conversation_contexts_intent_detected"), "conversation_contexts", ["intent_detected"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_contexts_intent_type"), "conversation_contexts", ["intent_type"], unique=False
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "conversation_id", sa.String(length=36), nullable=False, comment="Foreign key to conversations table"
        ),
        sa.Column(
            "direction",
            sa.Enum("INBOUND", "OUTBOUND", name="messagedirection"),
            nullable=False,
            comment="INBOUND or OUTBOUND",
        ),
        sa.Column("from_phone", sa.String(length=20), nullable=False, comment="Sender phone number"),
        sa.Column("to_phone", sa.String(length=20), nullable=False, comment="Recipient phone number"),
        sa.Column("body", sa.Text(), nullable=False, comment="Message text content"),
        sa.Column("media_url", sa.String(length=512), nullable=True, comment="URL of media attachment if present"),
        sa.Column("waha_message_id", sa.String(length=255), nullable=True, comment="WAHA message ID for deduplication"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_messages_conversation_id"), "conversation_messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_conversation_messages_created_at"), "conversation_messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_conversation_messages_direction"), "conversation_messages", ["direction"], unique=False)
    op.create_index(op.f("ix_conversation_messages_id"), "conversation_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_conversation_messages_waha_message_id"), "conversation_messages", ["waha_message_id"], unique=True
    )
    op.create_table(
        "conversation_tags",
        sa.Column("conversation_id", sa.String(length=36), nullable=False, comment="UUID of the conversation"),
        sa.Column("tag_id", sa.Integer(), nullable=False, comment="ID of the tag"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the tag was applied to the conversation",
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id", "tag_id"),
    )
    op.create_index(op.f("ix_conversation_tags_tag_id"), "conversation_tags", ["tag_id"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verification_token", sa.String(length=255), nullable=True),
        sa.Column("email_verification_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_token", sa.String(length=255), nullable=True),
        sa.Column("reset_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reset_token_used", sa.Boolean(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=255), nullable=True),
        sa.Column("backup_codes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credentials_id"), "credentials", ["id"], unique=False)
    op.create_index(op.f("ix_credentials_reset_token"), "credentials", ["reset_token"], unique=False)
    op.create_index(op.f("ix_credentials_user_id"), "credentials", ["user_id"], unique=True)
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "conversation_id",
            sa.String(length=36),
            nullable=True,
            comment="One lead per conversation (optional - leads can exist without conversations)",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Lead name"),
        sa.Column("phone_number", sa.String(length=20), nullable=False, comment="Contact phone number"),
        sa.Column("email", sa.String(length=255), nullable=True, comment="Email if provided"),
        sa.Column(
            "status",
            sa.Enum("NEW", "ENGAGED", "INTERESTED", "READY", "SCHEDULED", "LOST", name="leadstatus"),
            nullable=False,
            comment="Lead maturity status",
        ),
        sa.Column("maturity_score", sa.Integer(), nullable=False, comment="Lead score (0-100)"),
        sa.Column("notes", sa.Text(), nullable=True, comment="Internal notes about the lead"),
        sa.Column("assigned_to_user_id", sa.Integer(), nullable=True, comment="Assigned secretary user ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("converted_at", sa.DateTime(), nullable=True, comment="When lead was converted (scheduled)"),
        sa.CheckConstraint("maturity_score >= 0 AND maturity_score <= 100", name="check_maturity_score_range"),
        sa.ForeignKeyConstraint(["assigned_to_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_assigned_to_user_id"), "leads", ["assigned_to_user_id"], unique=False)
    op.create_index(op.f("ix_leads_conversation_id"), "leads", ["conversation_id"], unique=True)
    op.create_index(op.f("ix_leads_created_at"), "leads", ["created_at"], unique=False)
    op.create_index(op.f("ix_leads_id"), "leads", ["id"], unique=False)
    op.create_index(op.f("ix_leads_phone_number"), "leads", ["phone_number"], unique=False)
    op.create_index(op.f("ix_leads_status"), "leads", ["status"], unique=False)
    op.create_table(
        "llm_interactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "conversation_id", sa.String(length=36), nullable=False, comment="Foreign key to conversations table"
        ),
        sa.Column("prompt", sa.Text(), nullable=False, comment="Full prompt sent to LLM"),
        sa.Column("response", sa.Text(), nullable=False, comment="Full response from LLM"),
        sa.Column(
            "model_name", sa.String(length=100), nullable=False, comment="Model identifier (e.g., 'gemini-1.5-pro')"
        ),
        sa.Column("tokens_used", sa.Integer(), nullable=True, comment="Total tokens used"),
        sa.Column("latency_ms", sa.Integer(), nullable=True, comment="Request latency in milliseconds"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_interactions_conversation_id"), "llm_interactions", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_llm_interactions_created_at"), "llm_interactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_llm_interactions_id"), "llm_interactions", ["id"], unique=False)
    op.create_table(
        "message_location",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_location_message_id"), "message_location", ["message_id"], unique=True)
    op.create_table(
        "message_media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("mimetype", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_media_message_id"), "message_media", ["message_id"], unique=False)
    op.create_table(
        "playbooks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("topic_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playbooks_active"), "playbooks", ["active"], unique=False)
    op.create_index(op.f("ix_playbooks_name"), "playbooks", ["name"], unique=False)
    op.create_index(op.f("ix_playbooks_topic_id"), "playbooks", ["topic_id"], unique=False)
    op.create_table(
        "lead_interactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lead_id", sa.String(length=36), nullable=False, comment="Foreign key to leads table"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="User who performed the interaction"),
        sa.Column(
            "interaction_type",
            sa.Enum("NOTE", "STATUS_CHANGE", "CALL", "EMAIL", name="interactiontype"),
            nullable=False,
            comment="Type of interaction",
        ),
        sa.Column("notes", sa.Text(), nullable=False, comment="Details of the interaction"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lead_interactions_created_at"), "lead_interactions", ["created_at"], unique=False)
    op.create_index(op.f("ix_lead_interactions_id"), "lead_interactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_lead_interactions_interaction_type"), "lead_interactions", ["interaction_type"], unique=False
    )
    op.create_index(op.f("ix_lead_interactions_lead_id"), "lead_interactions", ["lead_id"], unique=False)
    op.create_index(op.f("ix_lead_interactions_user_id"), "lead_interactions", ["user_id"], unique=False)
    op.create_table(
        "playbook_embeddings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("playbook_id", sa.String(length=36), nullable=False),
        sa.Column("embedding_text", sa.Text(), nullable=False),
        sa.Column("chroma_doc_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["playbook_id"], ["playbooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playbook_embeddings_chroma_doc_id"), "playbook_embeddings", ["chroma_doc_id"], unique=True)
    op.create_index(op.f("ix_playbook_embeddings_playbook_id"), "playbook_embeddings", ["playbook_id"], unique=True)
    op.create_table(
        "playbook_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("playbook_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False, comment="Template message ID"),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("context_hint", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["playbook_id"], ["playbooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playbook_id", "step_order", name="uq_playbook_steps_playbook_order"),
    )
    op.create_index(op.f("ix_playbook_steps_message_id"), "playbook_steps", ["message_id"], unique=False)
    op.create_index(op.f("ix_playbook_steps_playbook_id"), "playbook_steps", ["playbook_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_playbook_steps_playbook_id"), table_name="playbook_steps")
    op.drop_index(op.f("ix_playbook_steps_message_id"), table_name="playbook_steps")
    op.drop_table("playbook_steps")
    op.drop_index(op.f("ix_playbook_embeddings_playbook_id"), table_name="playbook_embeddings")
    op.drop_index(op.f("ix_playbook_embeddings_chroma_doc_id"), table_name="playbook_embeddings")
    op.drop_table("playbook_embeddings")
    op.drop_index(op.f("ix_lead_interactions_user_id"), table_name="lead_interactions")
    op.drop_index(op.f("ix_lead_interactions_lead_id"), table_name="lead_interactions")
    op.drop_index(op.f("ix_lead_interactions_interaction_type"), table_name="lead_interactions")
    op.drop_index(op.f("ix_lead_interactions_id"), table_name="lead_interactions")
    op.drop_index(op.f("ix_lead_interactions_created_at"), table_name="lead_interactions")
    op.drop_table("lead_interactions")
    op.drop_index(op.f("ix_playbooks_topic_id"), table_name="playbooks")
    op.drop_index(op.f("ix_playbooks_name"), table_name="playbooks")
    op.drop_index(op.f("ix_playbooks_active"), table_name="playbooks")
    op.drop_table("playbooks")
    op.drop_index(op.f("ix_message_media_message_id"), table_name="message_media")
    op.drop_table("message_media")
    op.drop_index(op.f("ix_message_location_message_id"), table_name="message_location")
    op.drop_table("message_location")
    op.drop_index(op.f("ix_llm_interactions_id"), table_name="llm_interactions")
    op.drop_index(op.f("ix_llm_interactions_created_at"), table_name="llm_interactions")
    op.drop_index(op.f("ix_llm_interactions_conversation_id"), table_name="llm_interactions")
    op.drop_table("llm_interactions")
    op.drop_index(op.f("ix_leads_status"), table_name="leads")
    op.drop_index(op.f("ix_leads_phone_number"), table_name="leads")
    op.drop_index(op.f("ix_leads_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_created_at"), table_name="leads")
    op.drop_index(op.f("ix_leads_conversation_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_assigned_to_user_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_credentials_user_id"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_reset_token"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_id"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_conversation_tags_tag_id"), table_name="conversation_tags")
    op.drop_table("conversation_tags")
    op.drop_index(op.f("ix_conversation_messages_waha_message_id"), table_name="conversation_messages")
    op.drop_index(op.f("ix_conversation_messages_id"), table_name="conversation_messages")
    op.drop_index(op.f("ix_conversation_messages_direction"), table_name="conversation_messages")
    op.drop_index(op.f("ix_conversation_messages_created_at"), table_name="conversation_messages")
    op.drop_index(op.f("ix_conversation_messages_conversation_id"), table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_index(op.f("ix_conversation_contexts_intent_type"), table_name="conversation_contexts")
    op.drop_index(op.f("ix_conversation_contexts_intent_detected"), table_name="conversation_contexts")
    op.drop_index(op.f("ix_conversation_contexts_id"), table_name="conversation_contexts")
    op.drop_index(op.f("ix_conversation_contexts_conversation_id"), table_name="conversation_contexts")
    op.drop_table("conversation_contexts")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_refresh_token_jti"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_is_revoked"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_whatsapp_sessions_name"), table_name="whatsapp_sessions")
    op.drop_index(op.f("ix_whatsapp_sessions_is_active"), table_name="whatsapp_sessions")
    op.drop_index(op.f("ix_whatsapp_sessions_id"), table_name="whatsapp_sessions")
    op.drop_table("whatsapp_sessions")
    op.drop_index(op.f("ix_webhook_logs_session_name"), table_name="webhook_logs")
    op.drop_index(op.f("ix_webhook_logs_processed"), table_name="webhook_logs")
    op.drop_index(op.f("ix_webhook_logs_id"), table_name="webhook_logs")
    op.drop_index(op.f("ix_webhook_logs_event_type"), table_name="webhook_logs")
    op.drop_index(op.f("ix_webhook_logs_created_at"), table_name="webhook_logs")
    op.drop_table("webhook_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_topics_name"), table_name="topics")
    op.drop_index(op.f("ix_topics_category"), table_name="topics")
    op.drop_index(op.f("ix_topics_active"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_revoked_tokens_token"), table_name="revoked_tokens")
    op.drop_index(op.f("ix_revoked_tokens_id"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_messages_type"), table_name="messages")
    op.drop_index(op.f("ix_messages_title"), table_name="messages")
    op.drop_index(op.f("ix_messages_tags"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_phone_number"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_chat_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_alerts_level"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
