"""add whatsapp sessions and webhook logs tables

Revision ID: 4c2d7e8f9a1b
Revises: 3b5aae0b603e
Create Date: 2025-12-11 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c2d7e8f9a1b'
down_revision: Union[str, None] = '3b5aae0b603e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False,
                              comment='STOPPED, STARTING, SCAN_QR_CODE, WORKING, FAILED'),
                    sa.Column('webhook_url', sa.Text(), nullable=True),
                    sa.Column('qr_code', sa.Text(), nullable=True,
                              comment='Base64 QR code image'),
                    sa.Column('connected_phone', sa.String(length=20),
                              nullable=True, comment='Connected WhatsApp number'),
                    sa.Column('connected_at', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_whatsapp_sessions_id'),
                    'whatsapp_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_sessions_is_active'),
                    'whatsapp_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_whatsapp_sessions_name'),
                    'whatsapp_sessions', ['name'], unique=True)

    op.create_table('webhook_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('session_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('event_type', sa.String(length=50), nullable=False,
                              comment='message, message.ack, etc.'),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()),
                              nullable=False, comment='Full webhook payload'),
                    sa.Column('processed', sa.Boolean(), nullable=False),
                    sa.Column('error', sa.Text(), nullable=True,
                              comment='Processing error if any'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_webhook_logs_created_at'),
                    'webhook_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_type'),
                    'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'),
                    'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_processed'),
                    'webhook_logs', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_logs_session_name'),
                    'webhook_logs', ['session_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_session_name'),
                  table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_processed'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'),
                  table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_created_at'),
                  table_name='webhook_logs')
    op.drop_table('webhook_logs')

    op.drop_index(op.f('ix_whatsapp_sessions_name'),
                  table_name='whatsapp_sessions')
    op.drop_index(op.f('ix_whatsapp_sessions_is_active'),
                  table_name='whatsapp_sessions')
    op.drop_index(op.f('ix_whatsapp_sessions_id'),
                  table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    # ### end Alembic commands ###
