"""add conversations table

Revision ID: 5d3e9f1a2c4b
Revises: 4c2d7e8f9a1b
Create Date: 2025-12-12 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d3e9f1a2c4b'
down_revision: Union[str, None] = '4c2d7e8f9a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
                    sa.Column('id', sa.String(length=36), nullable=False,
                              comment='UUID primary key'),
                    sa.Column('chat_id', sa.String(length=100), nullable=False,
                              comment='WhatsApp chat ID (e.g., 5511999999999@c.us)'),
                    sa.Column('phone_number', sa.String(length=20), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True,
                              comment='Contact name'),
                    sa.Column('status', sa.Enum('ACTIVE', 'WAITING_SECRETARY', 'TRANSFERRED', 'CLOSED', 
                              name='conversationstatus'), nullable=False,
                              comment='Current conversation status'),
                    sa.Column('lead_status', sa.Enum('NEW', 'ENGAGED', 'INTERESTED', 'READY', 'SCHEDULED', 'LOST',
                              name='leadstatus'), nullable=False,
                              comment='Lead maturity level'),
                    sa.Column('escalation_reason', sa.String(length=50), nullable=True,
                              comment='Reason for escalation (scheduling_request, issue, sentiment)'),
                    sa.Column('escalated_at', sa.DateTime(), nullable=True,
                              comment='When conversation was escalated'),
                    sa.Column('last_message_at', sa.DateTime(), nullable=False,
                              comment='Timestamp of last message'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversations_id'),
                    'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_chat_id'),
                    'conversations', ['chat_id'], unique=True)
    op.create_index(op.f('ix_conversations_phone_number'),
                    'conversations', ['phone_number'], unique=False)
    op.create_index(op.f('ix_conversations_status'),
                    'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_lead_status'),
                    'conversations', ['lead_status'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'),
                    'conversations', ['last_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_lead_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_phone_number'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_chat_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.execute('DROP TYPE conversationstatus')
    op.execute('DROP TYPE leadstatus')
    # ### end Alembic commands ###
