"""add epic4 models conversation messages leads interactions

Revision ID: 6f4e7d8c9b2a
Revises: 5d3e9f1a2c4b
Create Date: 2025-12-16 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f4e7d8c9b2a'
down_revision: Union[str, None] = '5d3e9f1a2c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar enum MessageDirection (se não existir)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE messagedirection AS ENUM ('INBOUND', 'OUTBOUND');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Criar enum InteractionType (se não existir)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE interactiontype AS ENUM ('PHONE_CALL', 'WHATSAPP_MESSAGE', 'EMAIL', 'IN_PERSON', 'OTHER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Criar tabela conversation_messages
    op.create_table('conversation_messages',
                    sa.Column('id', sa.String(length=36), nullable=False,
                              comment='UUID primary key'),
                    sa.Column('conversation_id', sa.String(length=36), nullable=False,
                              comment='FK to conversations table'),
                    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), 
                              nullable=False,
                              comment='Message direction'),
                    sa.Column('from_phone', sa.String(length=20), nullable=False,
                              comment='Sender phone number'),
                    sa.Column('to_phone', sa.String(length=20), nullable=False,
                              comment='Recipient phone number'),
                    sa.Column('body', sa.Text(), nullable=True,
                              comment='Message text content'),
                    sa.Column('media_url', sa.String(length=500), nullable=True,
                              comment='URL to media file if present'),
                    sa.Column('waha_message_id', sa.String(length=100), nullable=True,
                              comment='WAHA message ID for tracking'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], 
                                          ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversation_messages_id'),
                    'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'),
                    'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_waha_message_id'),
                    'conversation_messages', ['waha_message_id'], unique=True)
    op.create_index(op.f('ix_conversation_messages_created_at'),
                    'conversation_messages', ['created_at'], unique=False)
    
    # Criar tabela leads
    op.create_table('leads',
                    sa.Column('id', sa.String(length=36), nullable=False,
                              comment='UUID primary key'),
                    sa.Column('conversation_id', sa.String(length=36), nullable=False,
                              comment='FK to conversations table (unique)'),
                    sa.Column('name', sa.String(length=255), nullable=False,
                              comment='Lead name'),
                    sa.Column('phone_number', sa.String(length=20), nullable=False,
                              comment='Lead phone number'),
                    sa.Column('email', sa.String(length=255), nullable=True,
                              comment='Lead email'),
                    sa.Column('status', sa.Enum('NEW', 'ENGAGED', 'INTERESTED', 'READY', 'SCHEDULED', 'LOST',
                              name='leadstatus'), nullable=False,
                              comment='Lead status'),
                    sa.Column('maturity_score', sa.Integer(), nullable=False, server_default='0',
                              comment='Lead maturity score (0-100)'),
                    sa.Column('notes', sa.Text(), nullable=True,
                              comment='Additional notes about the lead'),
                    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True,
                              comment='FK to users table (secretary assigned)'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('converted_at', sa.DateTime(), nullable=True,
                              comment='When lead was converted to appointment'),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], 
                                          ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], 
                                          ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.CheckConstraint('maturity_score >= 0 AND maturity_score <= 100', 
                                     name='check_maturity_score_range')
                    )
    op.create_index(op.f('ix_leads_id'),
                    'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_conversation_id'),
                    'leads', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_leads_status'),
                    'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to_user_id'),
                    'leads', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_leads_created_at'),
                    'leads', ['created_at'], unique=False)
    
    # Criar tabela lead_interactions
    op.create_table('lead_interactions',
                    sa.Column('id', sa.String(length=36), nullable=False,
                              comment='UUID primary key'),
                    sa.Column('lead_id', sa.String(length=36), nullable=False,
                              comment='FK to leads table'),
                    sa.Column('user_id', sa.String(length=36), nullable=True,
                              comment='FK to users table (who performed interaction)'),
                    sa.Column('interaction_type', sa.Enum('PHONE_CALL', 'WHATSAPP_MESSAGE', 'EMAIL', 'IN_PERSON', 'OTHER',
                              name='interactiontype'), nullable=False,
                              comment='Type of interaction'),
                    sa.Column('notes', sa.Text(), nullable=True,
                              comment='Interaction notes'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], 
                                          ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], 
                                          ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_lead_interactions_id'),
                    'lead_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_lead_interactions_lead_id'),
                    'lead_interactions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_interactions_created_at'),
                    'lead_interactions', ['created_at'], unique=False)
    
    # Criar tabela llm_interactions
    op.create_table('llm_interactions',
                    sa.Column('id', sa.String(length=36), nullable=False,
                              comment='UUID primary key'),
                    sa.Column('conversation_id', sa.String(length=36), nullable=False,
                              comment='FK to conversations table'),
                    sa.Column('prompt', sa.Text(), nullable=False,
                              comment='Prompt sent to LLM'),
                    sa.Column('response', sa.Text(), nullable=False,
                              comment='Response from LLM'),
                    sa.Column('model_name', sa.String(length=100), nullable=False,
                              comment='LLM model used'),
                    sa.Column('tokens_used', sa.Integer(), nullable=True,
                              comment='Total tokens consumed'),
                    sa.Column('latency_ms', sa.Integer(), nullable=True,
                              comment='Response time in milliseconds'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], 
                                          ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_llm_interactions_id'),
                    'llm_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_llm_interactions_conversation_id'),
                    'llm_interactions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_interactions_created_at'),
                    'llm_interactions', ['created_at'], unique=False)
    
    # Criar tabela conversation_contexts
    op.create_table('conversation_contexts',
                    sa.Column('id', sa.String(length=36), nullable=False,
                              comment='UUID primary key'),
                    sa.Column('conversation_id', sa.String(length=36), nullable=False,
                              comment='FK to conversations table'),
                    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
                              comment='JSON context stored in ChromaDB'),
                    sa.Column('embedding_id', sa.String(length=100), nullable=True,
                              comment='ChromaDB embedding ID'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], 
                                          ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_conversation_contexts_id'),
                    'conversation_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_contexts_conversation_id'),
                    'conversation_contexts', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_contexts_embedding_id'),
                    'conversation_contexts', ['embedding_id'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Dropar tabelas na ordem reversa (por causa das FKs)
    op.drop_index(op.f('ix_conversation_contexts_embedding_id'), table_name='conversation_contexts')
    op.drop_index(op.f('ix_conversation_contexts_conversation_id'), table_name='conversation_contexts')
    op.drop_index(op.f('ix_conversation_contexts_id'), table_name='conversation_contexts')
    op.drop_table('conversation_contexts')
    
    op.drop_index(op.f('ix_llm_interactions_created_at'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_conversation_id'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_id'), table_name='llm_interactions')
    op.drop_table('llm_interactions')
    
    op.drop_index(op.f('ix_lead_interactions_created_at'), table_name='lead_interactions')
    op.drop_index(op.f('ix_lead_interactions_lead_id'), table_name='lead_interactions')
    op.drop_index(op.f('ix_lead_interactions_id'), table_name='lead_interactions')
    op.drop_table('lead_interactions')
    
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_conversation_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_waha_message_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    
    # Dropar enums
    op.execute('DROP TYPE interactiontype')
    op.execute('DROP TYPE messagedirection')
    
    # ### end Alembic commands ###
